{{- if .Values.slidesToVideoManager.type }}
apiVersion: batch/v1
kind: Job
metadata:
  name: slides-to-video-migration
  labels:
    app.kubernetes.io/component: manager
{{- if .Values.slidesToVideoManager.annotations }}
  annotations:
    {{- toYaml .Values.slidesToVideoManager.annotations | nindent 4 }}
{{- end }}
spec:
  template:
    spec:
      securityContext:
        {{- toYaml .Values.slidesToVideoManager.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      containers:
      - name: slides-to-video-manager
        image: {{ .Values.slidesToVideoManager.image }}
        imagePullPolicy: {{ .Values.slidesToVideoManager.pullPolicy }}
        args:
          {{- if .Values.slidesToVideoManager.config}}
          ["app", "migrate", "-c", "/etc/conf/config.yaml"]
          {{- else }}
          ["app", "migrate"]
          {{- end }}
        resources:
          {{- toYaml .Values.slidesToVideoManager.resources | nindent 10 }}
        volumeMounts:
        {{- range .Values.slidesToVideoManager.extraSecretMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
            readOnly: {{ .readOnly }}
        {{- end }}
        {{- range .Values.slidesToVideoManager.extraConfigmapMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
            readOnly: {{ .readOnly }}
        {{- end }}
        {{- if .Values.slidesToVideoManager.config}}
          - name: slides-to-video-configuration
            mountPath: /etc/conf/
        {{- end }}
        volumes:
        {{- range .Values.slidesToVideoManager.extraConfigmapMounts }}
          - name: {{ .name }}
            configMap:
              name: {{ .configMap }}
        {{- end }}
        {{- range .Values.slidesToVideoManager.extraSecretMounts }}
          - name: {{ .name }}
            secret:
              secretName: {{ .secretName }}
        {{- end }}
        {{- if .Values.slidesToVideoManager.config}}
          - name: slides-to-video-configuration
            configMap:
              name: slides-to-video-configuration
        {{- end }}
      restartPolicy: Never
      {{- with .Values.slidesToVideoManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slidesToVideoManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slidesToVideoManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 4
{{- end }}