{{- if .Values.slidesToVideoManager.svcAcctFile }}
apiVersion: v1
kind: Secret
metadata:
  name: slides-to-video-manager
type: Opaque
stringData:
  cred.json: |-
{{ .Values.slidesToVideoManager.svcAcctFile | indent 4 }}
{{- end }}
