# Switch rest client as necessary
@hostname = "https://slides-to-video-manager-sj5kqt5fxq-an.a.run.app"
@v1baseurl = {{hostname}}/api/v1

### Create project
# @name createProject

POST {{v1baseurl}}/project

< ./tester.pdf

### Retrive projects
GET {{v1baseurl}}/projects

### Get single project

GET {{v1baseurl}}/project/{{createProject.response.body.id}}

### Update single project
PUT {{v1baseurl}}/projects/{{createProject.response.body.id}}
Content-Type: application/json

{
    "id": "{{createProject.response.body.id}}",
	"slide_assets": [
        {
            "image_id": "",
	        "text": "",
	        "video_id": "",
	        "slide_no": ""
        },
        {
            "image_id": "",
	        "text": "",
	        "video_id": "",
	        "slide_no": ""
        }
    ]
}

### Generate video generation

POST {{v1baseurl}}/project/{{createProject.response.body.id}}:generate


### Set job status
@job_id = 'abc'

### Update pdf split job
POST {{v1baseurl}}/{{job_id}}/abc:update-status
Content-Type: application/json

{
    "job_type": "pdf-split",
    "status": "success",
    "dedup_id": "{{$guid}}",
    "job_details": {
        "slide_details": [
            {
                "image": "image1.jpg",
                "slide_no": 0
            },
            {
                "image": "image2.jpg",
                "slide_no": 1
            },
            {
                "image": "image3.jpg",
                "slide_no": 2
            }
        ]
    }
}

### Update image to video job

POST {{v1baseurl}}/{{job_id}}/abc:update-status
Content-Type: application/json

{
    "job_type": "image-to-video",
    "status": "success",
    "dedup_id": "{{$guid}}",
    "job_details": {
        "image_id": "image1.jpg",
        "output_file": "image1.mp4"
    }
}

### Update video concat job

POST {{v1baseurl}}/{{job_id}}/abc:update-status
Content-Type: application/json

{
    "job_type": "video-concat",
    "status": "success",
    "dedup_id": "{{$guid}}",
    "job_details": {
        "output_video": "final_output.mp4"
    }
}
