steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/slides-to-video-manager:$SHORT_SHA",
        ".",
      ]
images: ["gcr.io/$PROJECT_ID/slides-to-video-manager:$SHORT_SHA"]
