apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slidesToVideo.concatenateVideoFullname" . }}
  labels:
    {{- include "slidesToVideo.concatenateVideoLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.concatenateVideo.replicaCount }}
  selector:
    matchLabels:
      {{- include "slidesToVideo.concatenateVideoSelectorLabels" . | nindent 4 }}
  strategy:
    type: Recreate
  template:
    metadata:
{{- if .Values.concatenateVideo.podAnnotations }}
      annotations:
        {{- toYaml .Values.concatenateVideo.podAnnotations | nindent 8 }}
{{- end }}
      labels:
        {{- include "slidesToVideo.concatenateVideoSelectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.concatenateVideo.podSecurityContext | nindent 8 }}
      {{- with .Values.concatenateVideo.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: slides-to-video-concatenateVideo
        image: {{ include "slidesToVideo.concatenateVideoImage" . }}
        imagePullPolicy: {{ .Values.concatenateVideo.image.pullPolicy }}
        args:
          {{- if .Values.concatenateVideo.config}}
          ["app", "server", "-c", "/etc/conf/config.yaml"]
          {{- else }}
          ["app", "server"]
          {{- end }}
        ports:
        - name: api
          containerPort: 8080
          protocol: TCP
        resources:
          {{- toYaml .Values.concatenateVideo.resources | nindent 10 }}
        volumeMounts:
        {{- range .Values.concatenateVideo.extraSecretMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
            readOnly: {{ .readOnly }}
        {{- end }}
        {{- range .Values.concatenateVideo.extraConfigmapMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
            readOnly: {{ .readOnly }}
        {{- end }}
        {{- if .Values.concatenateVideo.config}}
          - name: slides-to-video-configuration
            mountPath: /etc/conf/
        {{- end }}
        {{- if .Values.concatenateVideo.svcAcctFile}}
          - name: slides-to-video-secret
            mountPath: /etc/svcacct/
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: api
        readinessProbe:
          httpGet:
            path: /readyz
            port: api
      restartPolicy: Always
      volumes:
      {{- range .Values.concatenateVideo.extraConfigmapMounts }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap }}
      {{- end }}
      {{- range .Values.concatenateVideo.extraSecretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.concatenateVideo.config}}
        - name: slides-to-video-configuration
          configMap:
            name: slides-to-video-configuration
      {{- end }}
      {{- if .Values.concatenateVideo.svcAcctFile }}
        - name: slides-to-video-secret
          secret:
            secretName: slides-to-video-concatenateVideo
      {{- end }}
      {{- with .Values.concatenateVideo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.concatenateVideo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.concatenateVideo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}