version: '3.3'

services:
  frontend:
    image: frontend
    ports:
      - 8081:8080
    volumes:
      - ../../cmd/slides-to-video-frontend/main.min.js:/usr/share/nginx/html/assets/main.min.js
  manager:
    image: slides-to-video-manager
    ports:
      - 8880:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../cmd/slides-to-video-manager/configuration:/root/configuration
      - local-storage:/data/storage
    secrets:
      - manager_secrets.yaml
    command:
      - "app"
      - "server"
      - "-c"
      - "/root/configuration/config.yaml,/run/secrets/manager_secrets.yaml"
    restart: always
  migrate:
    image: slides-to-video-manager
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../cmd/slides-to-video-manager/configuration:/root/configuration
    command:
      - "app"
      - "migrate"
      - "-c"
      - "/root/configuration/config.yaml"
    restart: on-failure
  db:
    image: mariadb:12.2.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: some-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  local-storage:

secrets:
  manager_secrets.yaml:
    file: manager_secrets.yaml

