version: '3.3'

services:
  frontend:
    image: frontend
    ports:
      - 8081:8080
  manager:
    image: slides-to-video-manager
    ports:
      - 8880:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../cmd/slides-to-video-manager/configuration:/root/configuration
      - local-storage:/data/storage
    secrets:
      - manager_secrets.yaml
    command:
      - "app"
      - "server"
      - "-c"
      - "/run/secrets/manager_secrets.yaml"
    restart: always
  pdfsplitter:
    image: pdf-splitter
    ports:
      - 8881:8081
    volumes:
      - ../../cmd/pdf-splitter/configuration:/root/configuration
      - local-storage:/data/storage
    command:
      - "app"
      - "server"
      - "-c"
      - "/root/configuration/config.yaml"
    restart: on-failure
  migrate:
    image: slides-to-video-manager
    depends_on:
      db:
        condition: service_healthy
    command:
      - "app"
      - "migrate"
      - "-c"
      - "/root/configuration/config.yaml"
    restart: on-failure
  image2video:
    image: image-to-video
    ports:
      - 8882:8082
    volumes:
      - ../../cmd/image-to-video/configuration:/root/configuration
      - local-storage:/data/storage
    secrets:
      - image_to_video_cred
    command:
      - "app"
      - "server"
      - "-c"
      - "/root/configuration/config.yaml"
    restart: on-failure
  concatenatevideo:
    image: concatenate-video
    ports:
      - 8883:8083
    volumes:
      - ../../cmd/concatenate-video/configuration:/root/configuration
      - local-storage:/data/storage
    command:
      - "app"
      - "server"
      - "-c"
      - "/root/configuration/config.yaml"
    restart: on-failure
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: some-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  queue:
    image: nats:2.1.9

volumes:
  local-storage:

secrets:
  manager_secrets.yaml:
    file: manager_secrets.yaml
  image_to_video_cred:
    file: image_to_video_cred

