server:
  host: "0.0.0.0"
  port: 8080
  scheme: "http"
  trace: false
  svcAccFile: ""
  clientID: ""
  clientSecret: ""
  scope: ""
  redirectURI: ""
  authSecret: ""
  issuer: ""
  expiryTime: 3600
workers:
  enabled: false
datastore:
  type: "mysql"
  mysql:
    user: "user"
    password: "password"
    host: "db"
    port: 3306
    dbName: "some-database"
queue:
  type: "nats"
  nats:
    endpoint: "nats://queue:4222"
    pdfToImageTopic: "pdf-splitter"
    imageToVideoTopic: "image-to-video"
    videoConcatTopic: "concatenate-video"
blobStorage:
  type: "minio"
  minio:
    bucket: "videos"
    pdfFolder: "pdf"
    imagesFolder: "images"
    videoSnippetsFolder: "video-snippets"
    videoFolder: "videos"
    endpoint: "s3:9000"
    accessKeyId: "s3_user"
    secretAccessKey: "s3_password"

