slidesToVideoManager:
  podSecurityContext: {}
  securityContext: {}
  annotations: {}
  name: slides-to-video-manager
  image: slides-to-video-manager
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  resources: {}
  service:
    annotations: {}
    type: ClusterIP
    port: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podLabels: {}
  extraSecretMounts: []
