version: '3.3'

services:
  manager:
    image: slides-to-video-manager
    ports:
      - 8880:8080
    volumes:
      - ../cmd/slides-to-video-manager/configuration:/root/configuration
    command:
      - "app"
      - "server"
      - "-c"
      - "/root/configuration/config.yaml"
    restart: always
  pdfsplitter:
    image: pdf-splitter
    ports:
      - 8881:8081
    volumes:
      - ../cmd/pdf-splitter/configuration:/root/configuration
    command:
      - "app"
      - "server"
      - "-c"
      - "/root/configuration/config.yaml"
  migrate:
    image: slides-to-video-manager
    volumes:
      - ../cmd/slides-to-video-manager/configuration:/root/configuration
    command:
      - "app"
      - "migrate"
      - "-c"
      - "/root/configuration/config.yaml"
    restart: on-failure
  image2video:
    image: image-to-video
    ports:
      - 8882:8082
    volumes:
      - ../cmd/image-to-video/configuration:/root/configuration
    secrets:
      - image_to_video_cred
    command:
      - "app"
      - "server"
      - "-c"
      - "/root/configuration/config.yaml"
    restart: on-failure
  concatenatevideo:
    image: concatenate-video
    ports:
      - 8883:8083
    volumes:
      - ../cmd/concatenate-video/configuration:/root/configuration
    command:
      - "app"
      - "server"
      - "-c"
      - "/root/configuration/config.yaml"
    restart: on-failure
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: some-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  s3:
    image: minio/minio:RELEASE.2020-11-19T23-48-16Z
    ports:
      - 9999:9000
    environment:
      MINIO_ACCESS_KEY: s3_user
      MINIO_SECRET_KEY: s3_password
    command:
      - "server"
      - "/data"
  createbuckets:
    image: minio/mc:RELEASE.2020-11-17T00-39-14Z
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://s3:9000 s3_user s3_password;
      /usr/bin/mc rm -r --force minio/videos;
      /usr/bin/mc mb minio/videos;
      /usr/bin/mc policy download minio/videos;
      exit 0;
      "
    restart: on-failure
  queue:
    image: nats:2.1.9

secrets:
  image_to_video_cred:
    file: image-to-video.json

    