apiVersion: v1
kind: Service
metadata:
  name: {{ include "slidesToVideo.managerFullname" . }}
  labels:
    {{- include "slidesToVideo.managerLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "slidesToVideo.managerSelectorLabels" . | nindent 4 }}
