{{- if .Values.manager.svcAcctFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slidesToVideo.managerFullname" . }}
  labels:
    {{- include "slidesToVideo.managerLabels" . | nindent 4 }}
type: Opaque
stringData:
  cred.json: |-
{{ .Values.manager.svcAcctFile | indent 4 }}
{{- end }}
