{{- if .Values.manager.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slidesToVideo.managerFullname" . }}
  labels:
    {{- include "slidesToVideo.managerLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
data:
  config.yaml: |-
{{ .Values.manager.config | indent 4 }}
{{- end }}